---
title: "Tidy Tuesday 01-01-2022"
author: "Jur Brauers"
date: "1/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Depencencies
library(here)
library(tidytuesdayR)

library(tidyverse)
library(ggplot2)
library(geojsonio)
library(broom)
library(rgeos)
library(mapproj)
library(viridis)
library(cowplot)

library(rvest)
library(tidyverse)
library(fs)
library(RColorBrewer)
library(rgdal)


```


```{r}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2022-01-11')


colony <- tuesdata$colony
```

```{r}

# download site
url <- "https://usda.library.cornell.edu/concern/publications/rn301137d?locale=en"

# raw html
raw_html <- read_html(url)

# all the download urls for zip files
all_urls <- raw_html %>% 
  html_elements("#content-wrapper > div.row.p-content > div.col-sm-7 > table") %>% 
  html_elements("a") %>% 
  html_attr("href") %>% 
  str_subset(".zip") 

# download to correct directory
download.file(all_urls, destfile = paste0("2022/2022-01-11/", basename(all_urls)))

# unzip into their respective folders
walk(basename(all_urls), ~ unzip(
  paste0("2022/2022-01-11/", .x),
  exdir = paste0("2022/2022-01-11/bee-", str_sub(.x, -6, -5))
))


#  Clean Colony data ------------------------------------------------------


clean_bee_colonies <- function(file){
  
  col_labs <- c("state", "colony_n", "colony_max", "colony_lost", 
    "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct")
  
  raw_df <- read_csv(file,  skip = 2, col_names = FALSE)
  
  date_rng <- read_csv(file, skip = 0, col_names = FALSE) %>% 
    slice(2) %>% 
    pull(X3) %>% 
    str_replace(" [5-6]/$", "") %>% 
    word(-2, -1)
  
  clean_df <- suppressWarnings(raw_df %>% 
    filter(!is.na(X4))  %>%
    filter(X2 == "d") %>% 
    select(X3:X10) %>% 
    set_names(nm = col_labs) %>% 
    mutate(date_range = date_rng, .before = state) %>% 
    separate(date_range, into = c("months", "year"), sep = " ") %>% 
    select(year, months, state, everything()) %>% 
    mutate(across(contains("colony"), as.integer)))
  
  clean_df
}


# Clean stress data -------------------------------------------------------


clean_bee_stress <- function(file){
  
  col_labs <- c("state", "colony_n", "colony_max", "colony_lost", 
    "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct")

  
  raw_df <- read_csv(file,  skip = 4, col_names = FALSE)
  
  date_rng <- read_csv(file, skip = 0, col_names = FALSE) %>% 
    slice(2) %>% 
    pull(X3) %>% 
    str_replace(" [5-6]/$", "") %>% 
    word(-2, -1)
  
  stress_nm <- c("state", "Varroa mites", "Other pests/parasites", "Disesases",
    "Pesticides", "Other", "Unknown")
  
  clean_df <- suppressWarnings(raw_df %>% 
      filter(!is.na(X4))  %>%
      filter(X2 == "d") %>% 
      select(X3:X9) %>% 
      set_names(nm = stress_nm) %>% 
      pivot_longer(cols = -state, names_to = "stressor", values_to = "stress_pct") %>% 
      mutate(date_range = date_rng, .before = state) %>% 
      separate(date_range, into = c("months", "year"), sep = " ") %>% 
      select(year, months, state, everything()) %>% 
      mutate(stress_pct = as.double(stress_pct)))
  
  clean_df
}


# Get the file index ------------------------------------------------------


all_html_index <- dir_ls(here("2022", "2022-01-11"), recurse = TRUE, glob = "*htm") %>% 
  str_subset("bee-") %>% 
  str_subset("index")

get_index <- function(index_file){
  ind_yr <- str_sub(index_file, -17, -16)
  
  raw_text <- index_file %>% 
    read_html() %>%
    html_text() %>% 
    str_split("\r\n[0-9]+") %>% 
    unlist() %>% 
    map(~str_split(.x, "\r\n")) 
  
  raw_text %>% 
    tibble(data = .) %>% 
    unchop(data) %>% 
    unnest_wider(data) %>% 
    select(file = ...2, desc = ...3) %>% 
    mutate(type = case_when(
      str_detect(desc, "Colonies, Maximum, Lost") ~ "Colony",
      str_detect(desc, "Colony Health Stressors") ~ "Stressor",
      TRUE ~ NA_character_
    )) %>% 
    filter(!is.na(type)) %>% 
    mutate(year = ind_yr, .before = file)
  
}

all_index_files <- map_dfr(all_html_index, get_index)

# Split data by type
split_files <- all_index_files %>% 
  mutate(dir_file = glue::glue("2022/2022-01-11/bee-{year}/{file}")) %>% 
  select(type, dir_file, year, file, desc) %>% 
  group_split(type)

# aggregate the clean data by type

all_colonies <-  map_dfr(split_files[[1]]$dir_file, clean_bee_colonies) %>% 
  distinct(year, months, state, .keep_all = TRUE) %>% 
  mutate(state = str_remove(state, " 4/| 5/")) %>% 
  filter(state %in% c(state.name, "Other States", "United States"))

all_stress <-  map_dfr(split_files[[2]]$dir_file, clean_bee_stress) %>% 
  distinct(year, months, state, stressor, .keep_all = TRUE) %>% 
  mutate(state = str_remove(state, " 4/| 5/")) %>% 
  filter(state %in% c(state.name, "Other States", "United States"))

# check data
all_colonies %>% 
  count(year, months) %>% 
  filter(n > 47)

all_stress %>% 
  count(year, months) %>% 
  filter(n > 282)

all_colonies %>% 
  write_csv("2022/2022-01-11/colony.csv")

all_stress %>% 
  write_csv("2022/2022-01-11/stressor.csv")
```

```{r}
# library
library(tidyverse)


# Download the Hexagones boundaries at geojson format here: https://team.carto.com/u/andrew/tables/andrew.us_states_hexgrid/public/map.

# Load this file. (Note: I stored in a folder called DATA)
spdf <- geojson_read(here("us_states_hexgrid.geojson"),  what = "sp")


# Bit of reformating
spdf@data = spdf@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))

# Show it
plot(spdf)
```


```{r}
# this is the approach by Lee Melvin Peralta, @melvinmperalta, just to see how Tidy Tuesday works. All credits go to him!

#data wrangling
colony_total_year <- colony %>% group_by(year) %>% summarize(total = sum(colony_n, na.rm = TRUE))
colony_total_season <- colony %>% group_by(months, year) %>% summarize(total = sum(colony_n, na.rm = TRUE))
colony_pct_loss_year <- colony %>% group_by(year) %>% summarize(lost_pct = mean(colony_lost_pct, na.rm = TRUE))
colony_pct_loss_season <- colony %>% group_by(months, year) %>% summarize(total = mean(colony_lost_pct, na.rm = TRUE))

colony_2020 <- colony %>% filter(year == 2020)
colony_spring <- colony_2020 %>% filter(months == "April-June") %>% select(state, colony_lost_pct)
colony_summer <- colony_2020 %>% filter(months == "July-September") %>% select(state, colony_lost_pct)
colony_fall <- colony_2020 %>% filter(months == "October-December") %>% select(state, colony_lost_pct)
colony_winter <- colony_2020 %>% filter(months == "January-March") %>% select(state, colony_lost_pct)

#hexagon map,courtesty of https://www.r-graph-gallery.com/328-hexbin-map-of-the-usa.html

spdf <- geojson_read("us_states_hexgrid.geojson",  what = "sp")
spdf@data = spdf@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
plot(spdf)

spdf_fortified <- tidy(spdf, region = "google_name")
centers <- cbind.data.frame(data.frame(gCentroid(spdf, byid=TRUE), id=spdf@data$iso3166_2))

ggplot() +
  geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="skyblue", color="white") +
  geom_text(data=centers, aes(x=x, y=y, label=id)) +
  theme_void() +
  coord_map()

#merge geospatial and colony data
df_spring <- spdf_fortified %>% 
  left_join(., colony_spring, by = c("id" = "state"))
df_summer <- spdf_fortified %>% 
  left_join(., colony_summer, by = c("id" = "state"))
df_fall <- spdf_fortified %>% 
  left_join(., colony_fall, by = c("id" = "state"))
df_winter <- spdf_fortified %>% 
  left_join(., colony_winter, by = c("id" = "state"))

#test initial choropleth map for spring
ggplot() +
  geom_polygon(data = df_spring, 
               aes(x = long, y = lat, group = group, fill = colony_lost_pct)) +
  geom_text(data = centers, aes(x = x, y = y, label = id)) +
  theme_void() +
  scale_fill_viridis() +
  coord_map() +
  theme(legend.position = "none")

#add full names to centers
centers <- centers %>% mutate(
  state = state.name[match(id, state.abb)]
)

#detail map for spring
centers_spring <- centers %>% 
  left_join(colony_spring, by = "state")

spring <- ggplot() +
  geom_polygon(data = subset(df_spring, !is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group, fill = colony_lost_pct), color = "white") +
  geom_polygon(data = subset(df_spring, is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group), fill = "dark green", color = "white") +
  geom_text(data = centers, aes(x = x, y = y, label = id), vjust = -0.6, size = 3.2, color = "white") +
  geom_text(data = centers_spring, aes(x = x, y = y, label = colony_lost_pct), 
            vjust = 1, size = 4, fontface = c("bold"), color = "white") +
  geom_text(data = subset(centers_spring, is.na(colony_lost_pct)), aes(x = x, y = y, label = "NA"), 
            vjust = 1, size = 3, color = "white") +
  theme_void() +
  scale_fill_viridis(begin = 0.6, end = 0.9, option = "A") +
  coord_map() +
  theme(legend.position = "none")

#detail map for summer
centers_summer <- centers %>% 
  left_join(colony_summer, by = "state")

summer <- ggplot() +
  geom_polygon(data = subset(df_summer, !is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group, fill = colony_lost_pct), color = "white") +
  geom_polygon(data = subset(df_summer, is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group), fill = "darkgoldenrod2", color = "white") +
  geom_text(data = centers, aes(x = x, y = y, label = id), vjust = -0.6, size = 3.2, color = "white") +
  geom_text(data = centers_summer, aes(x = x, y = y, label = colony_lost_pct), 
            vjust = 1, size = 4, fontface = c("bold"), color = "white") +
  geom_text(data = subset(centers_summer, is.na(colony_lost_pct)), aes(x = x, y = y, label = "NA"), 
            vjust = 1, size = 3, color = "white") +
  theme_void() +
  scale_fill_viridis(begin = 0.3, end = 0.8) +
  coord_map() +
  theme(legend.position = "none")

#detail map for fall
centers_fall <- centers %>% 
  left_join(colony_fall, by = "state")

fall <- ggplot() +
  geom_polygon(data = subset(df_fall, !is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group, fill = colony_lost_pct), color = "white") +
  geom_polygon(data = subset(df_fall, is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group), fill = "burlywood3", color = "white") +
  geom_text(data = centers, aes(x = x, y = y, label = id), vjust = -0.6, size = 3.2, color = "white") +
  geom_text(data = centers_fall, aes(x = x, y = y, label = colony_lost_pct), 
            vjust = 1, size = 4, fontface = c("bold"), color = "white") +
  geom_text(data = subset(centers_fall, is.na(colony_lost_pct)), aes(x = x, y = y, label = "NA"), 
            vjust = 1, size = 3, color = "white") +
  theme_void() +
  scale_fill_viridis(begin = 0.3, end = 0.7, option = "B") +
  coord_map() +
  theme(legend.position = "none")

#detail map for winter
#detail map for fall
centers_winter <- centers %>% 
  left_join(colony_winter, by = "state")

colorPalette <- mako(30, begin = 0.2, end = 0.7)

winter <- ggplot() +
  geom_polygon(data = subset(df_winter, !is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group, fill = colony_lost_pct), color = "white") +
  geom_polygon(data = subset(df_winter, is.na(colony_lost_pct)), 
               aes(x = long, y = lat, group = group), fill = "grey", color = "white") +
  geom_text(data = centers, aes(x = x, y = y, label = id), vjust = -0.6, size = 3.2, color = "white") +
  geom_text(data = centers_winter, aes(x = x, y = y, label = colony_lost_pct), 
            vjust = 1, size = 4, fontface = c("bold"), color = "white") +
  geom_text(data = subset(centers_winter, is.na(colony_lost_pct)), aes(x = x, y = y, label = "NA"), 
            vjust = 1, size = 3, color = "white") +
  theme_void() +
  scale_fill_gradientn(colors = colorPalette) +
  coord_map() +
  theme(legend.position = "none")

#export plots
tiff("spring.tiff", height = 1000, width = 1000, units = "px", pointsize = 12, res = 300, compression = 'lzw')
spring
dev.off()

tiff("summer.tiff", height = 1000, width = 1000, units = "px", pointsize = 12, res = 300, compression = 'lzw')
summer
dev.off()

tiff("fall.tiff", height = 1000, width = 1000, units = "px", pointsize = 12, res = 300, compression = 'lzw')
fall
dev.off()

tiff("winter.tiff", height = 1000, width = 1000, units = "px", pointsize = 12, res = 300, compression = 'lzw')
winter
dev.off()

```

